### ISSUE TITLE
output dimension of classifier

### ISSUE THREAD

**Issue by Sandy26** [donglixp/coarse2fine#12]
Hi Li,

Apologies to bother you with so many questions. I understand the output dim of 6 for agg_classifier since we get probabilties for 6 possible agg options. 

But why is the output dimn of sel_match 1  and output dim of lay_classifier 2? Aren't there like 35 sketches to classify from? I have the models below 
(sel_match): MatchScorer (
    (score_layer): Sequential (
      (0): Dropout (p = 0.5)
      (1): Linear (500 -> 64)
      (2): Tanh ()
      (3): Linear (64 -> 1)
    )
    (log_sm): LogSoftmax ()

  (lay_classifier): Sequential (
    (0): Dropout (p = 0.5)
    (1): Linear (250 -> 2)
    (2): LogSoftmax ()
  )

Thank you,
Shruti

**Comment by donglixp** [comment]
sel_match is defined as in https://github.com/donglixp/coarse2fine/blob/master/wikisql/table/Models.py#L133 . Its output is the matching probabilities of table columns [ prb_col0, prb_col1, ..., prb_colM], so the dimension of this module is 1.

**Comment by donglixp** [comment]
lay_classifier is defined as in https://github.com/donglixp/coarse2fine/blob/master/wikisql/table/ModelConstructor.py#L106 . It's two because len(fields['lay'].vocab)==2 according to your data. The dictionary fields['lay'].vocab is obtained in https://github.com/donglixp/coarse2fine/blob/master/wikisql/table/IO.py#L382 .
